name: Test runner

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build ./test/Localizer.Test/Localizer.Test.csproj --configuration Release

    - name: Test
      run: dotnet test ./test/Localizer.Test/Localizer.Test.csproj  --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Test Results' 
        path: '**/test_results.trx'
        reporter: 'dotnet-trx' 
