name: .NET Core

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./test/Localizer.Test/Localizer.Test.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ./test/Localizer.Test/Localizer.Test.csproj  --no-restore --verbosity normal
